# Generated by Django 4.2.7 on 2023-12-03 15:56

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[store.validators.validate_phone_number]),
        ),
    ]
